name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_npm:
    permissions:
      id-token: write
      contents: read
    uses: koikirin/buildplate/.github/workflows/publish_npm.buildplate.yml@v1