name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish_npm:
    # 只在原仓库执行
    if: ${{ github.repository == 'tediorelee/koishi-plugin-douyin' && !github.event.repository.fork }}
    permissions:
      id-token: write
      contents: read
    uses: koikirin/buildplate/.github/workflows/publish_npm.buildplate.yml@v1